name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}-v2
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile

      - name: Build
        run: npm i -g serve & yarn build

      - name: Run E2E Tests
        uses: cypress-io/github-action@v2
        with:
          record: false
          env: HOST=http://localhost:5000
          start: yarn start
          wait-on: http://localhost:5000
